version: 2

# Defining default values for all jobs
defaults: &defaults
  docker:
    - image: circleci/node:latest

jobs:
  setup_dx:
    # This command runs the preparation steps needed for the CI workflow:
    #
    # - Installation of the Salesforce CLI using npm
    # - Authentication of the DevHub
    # - Creation of a scratch org
    #
    # While a scratch org isn't needed in all steps it's still part of the process. The reason for this is
    # that we need to store the sfdx configuration files for it in the workspace, so that data can be shared
    # across different workflow steps.
    #
    # Keep it simple!
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install Sonar Scan
          command: |
              wget -q https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-3.3.0.1492-linux.zip
              unzip sonar-scanner-cli-3.3.0.1492-linux.zip
              rm sonar-scanner-cli-3.3.0.1492-linux.zip
              ls -altr 
      - run:
          name: Install Salesforce DX
          command: |
              export SFDX_USE_GENERIC_UNIX_KEYCHAIN=true
              export SFDX_DOMAIN_RETRY=300
              npm install sfdx-cli
              node_modules/sfdx-cli/bin/run --version
              node_modules/sfdx-cli/bin/run plugins --core
      - run:
          name: Authenticate DevHub
          command: |
              node_modules/sfdx-cli/bin/run force:auth:jwt:grant --clientid $CONSUMERKEY --jwtkeyfile assets/server.key --username $USERNAME --setdefaultdevhubusername -a HubOrg
      - run:
          name: Authenticate TestOrg
          command: |
              node_modules/sfdx-cli/bin/run force:auth:sfdxurl:store -f sfdxurl.txt -a TestOrg
      - run:
          name: Run tests
          command: |
              node_modules/sfdx-cli/bin/run force:apex:test:run -u TestOrg -c -r junit -d tests/Salesforce
      - run:
          name: Remove XML
          command: |
              cd tests
              bash <(curl -s https://codecov.io/bash) -t 0b319369-930a-4af8-b71f-7dc02134a985
              rm Salesforce/test-result-7*.xml
          when: always
      - store_test_results:
          path: tests
      - store_artifacts:
          path: tests
      - persist_to_workspace:
          # This is an important step. If we don't store the project data (cloned GitHub source and node_modules from the CLI installation)
          # we'd have to re-run installation for every workflow step.
          #
          # Also this step is crucial as we use it to share sfdx config parameters between steps.
          root: ~/
          paths:
              - .sfdx/*
              - project/*
  deploy_source:
  # This deploys the source to the ci scratch org.
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Push Source
          command: |
             node_modules/sfdx-cli/bin/run force:source:push -u ciorg
  create_and_test_package:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Create and install package
          command: |
            if [[ $SFDX_TEST_PACKAGING == "true" ]]; then
              scripts/packagingDeployment.sh
            fi
          no_output_timeout: 15m

  run_apex_tests:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Run Apex Tests
          command: |
              node_modules/sfdx-cli/bin/run force:apex:test:run -u ciorg -c -r junit -d tests/Salesforce
      - store_test_results:
          path: tests
      - store_artifacts:
          path: tests
  cleanup_scratch_org:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Clean Up
          command: |
              node_modules/sfdx-cli/bin/run force:org:delete -u ciorg -p

workflows:
  version: 2
  build_and_test:
    jobs:
      - setup_dx
      - deploy_source:
          requires:
            - setup_dx
          filters:
            branches:
              ignore: master
      - create_and_test_package:
          requires:
            - setup_dx
          filters:
            branches:
              ignore: master
      - run_apex_tests:
          requires:
            - deploy_source
          filters:
            branches:
              ignore: master
      - cleanup_scratch_org:
          requires:
            - setup_dx
            - deploy_source
            - create_and_test_package
            - run_apex_tests
